# Generated by Django 6.0.5 on 2026-06-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_signals', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
